---
title: "University Lake - Seed Banks"
author: "Nathan Wisnosk, Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

# Setup Work Environment

```{r}
rm(list=ls())
getwd()
setwd("~/GitHub/ul-seedbank/")
```

# Load data
```{r}
data <- read.table("data/ul-seedbank.env.txt", sep="\t", header=TRUE)
```


# Plot 1: Temp, SpC, Oxy, Secchi, pH
```{r}
png(filename="figures/env.fig.1.png", width = 800, height = 1800, res = 96*2)

layout(matrix(c(1:5), byrow = T))
par(mar = c(0.5, 4, 1, 1), oma = c(3, 4, 1, 1))

# Temperature
plot(data$sample.id, data$temp, xlim = c(0, 125), ylim = c(0, 35), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('Temp (C)'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(0, 10, 20, 30))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(0, 10, 20, 30))
axis(side = 1, lwd.ticks = 2, tck = -0.02, cex.axis = 0.9, las = 1,
    labels = F, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

# Conductivity (spc)
plot(data$sample.id, data$spc, xlim = c(0, 125), ylim = c(0.3, 0.7), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('Conductivity (?)'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(0.3, 0.5, 0.7))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(0.3, 0.5, 0.7))
axis(side = 1, lwd.ticks = 2, tck = -0.02, cex.axis = 0.9, las = 1,
    labels = F, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

# Oxygen (ppm)
plot(data$sample.id, data$oxygen, xlim = c(0, 125), ylim = c(0, 16), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('Dissolved oxygen (mg/L)'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(0, 5, 10, 15))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(0, 5, 10, 15))
axis(side = 1, lwd.ticks = 2, tck = -0.02, cex.axis = 0.9, las = 1,
    labels = F, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

# Secchi
plot(data$sample.id, data$secchi, xlim = c(0, 125), ylim = c(0, 4), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('Secchi'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(0, 1, 2, 3, 4))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(0, 1, 2, 3, 4))
axis(side = 1, lwd.ticks = 2, tck = -0.02, cex.axis = 0.9, las = 1,
    labels = F, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

# pH
plot(data$sample.id, data$ph, xlim = c(0, 125), ylim = c(6, 11), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('pH'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(6, 7, 8, 9, 10, 11))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(6, 7, 8, 9, 10, 11))
axis(side = 1, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    labels = T, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

mtext("Time (Sample ID)", side = 1, outer = TRUE, cex = 1.5, 
      line = 2, adj = 0.65)

# Close Plot Device
dev.off()
graphics.off()
```

# Plot 2: Chla, TP, TN, DOC
```{r}
png(filename="figures/env.fig.2.png", width = 800, height = 1800, res = 96*2)

layout(matrix(c(1:4), byrow = T))
par(mar = c(0.5, 4, 1, 1), oma = c(3, 4, 1, 1))

# Total Phosphorus (TP)
plot(data$sample.id, data$tp, xlim = c(0, 125), ylim = c(0, 100), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('TP (ug/L)'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(0, 100))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(0, 100))
axis(side = 1, lwd.ticks = 2, tck = -0.02, cex.axis = 0.9, las = 1,
    labels = F, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

# Total Nitrogen (TN)
plot(data$sample.id, data$tn, xlim = c(0, 125), ylim = c(0, 2), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('Total Nitrogen (mg/L'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(0, 1, 2))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(0, 1, 2))
axis(side = 1, lwd.ticks = 2, tck = -0.02, cex.axis = 0.9, las = 1,
    labels = F, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

# Dissolved Organic Carbon
plot(data$sample.id, data$oxygen, xlim = c(0, 125), ylim = c(0, 20), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('Dissolved organic carbon (mg/L)'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(0, 10, 20))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(0, 10, 20))
axis(side = 1, lwd.ticks = 2, tck = -0.02, cex.axis = 0.9, las = 1,
    labels = F, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

# Chlorophyll a
plot(data$sample.id, data$chla, xlim = c(0, 125), ylim = c(0, 200), type = "b", 
     pch = 22, bg = "grey", col = "black", cex = 1, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

mtext(expression('Chlorophyll a (ug/L)'), side = 2,
      outer = F, cex = 1.5, line = 3, adj = 0.5)  

# Major Axes
axis(side = 2, lwd.ticks = 2, tck = -0.02, cex.axis = 1.5, las = 1,
    labels = T, at = c(0, 100, 200))
axis(side = 4, lwd.ticks = 2, cex.axis = 1, las = 1,
   labels = F, at = c(0, 100, 200))
axis(side = 1, lwd.ticks = 2, tck = -0.02, cex.axis = 0.9, las = 1,
    labels = F, at = c(1, 25, 50, 75, 100, 125))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 25, 50, 75, 100, 125), labels = F)

mtext("Time (Sample ID)", side = 1, outer = TRUE, cex = 1.5, 
      line = 2, adj = 0.65)

# Close Plot Device
dev.off()
graphics.off()
```


