---
title: "University Lake Microbial Seed Bank"
author: "Nathan Wisnoski, Jay Lennon"
date: "1/19/2018"
output: html_document
---

```{r setup, include=FALSE}
# Load packages

rm(list = ls())
require(vegan)
require(reshape2)
require(tidyverse)
require(lubridate)
require(codyn)
require(viridis)
require(betapart)
require(cowplot)
require(xts)
require(progress)
require(cluster)
```

```{r data format, include=FALSE}
# Load data
OTUs.tax <- readRDS(file = "data/Rdata/OTUtax.rda")
# OTUs <- readRDS(file = "data/Rdata/OTUs.rda")

# Make rel abund matrices and split into active total comms
# OTUs <- OTUs[,-which(colSums(OTUs) < 5)]

# OTUs <- rrarefy(OTUs, sample = min(rowSums(OTUs)))
# saveRDS(OTUs, file = "data/Rdata/OTUs_rarefied.rda")
OTUs <- readRDS(file = "data/Rdata/OTUs_rarefied.rda")

OTUs.active <- OTUs[which(design$sample.type == "RNA"),]
OTUs.total <- OTUs[which(design$sample.type == "DNA"),]
OTUs.total <- decostand(OTUs.active, method = "pa") + OTUs.total

#OTUs.REL <- decostand(OTUs, method = "hellinger")
OTUs.REL <- decostand(OTUs, method = "total")
OTUs.REL.total <- OTUs.REL[which(design$sample.type == "DNA"),]
OTUs.REL.active <- OTUs.REL[which(design$sample.type == "RNA"),]

# read in environmental data
env.data <- read.table("data/ul-seedbank.env.txt", sep="\t", header=TRUE)
env.data$date <- parse_date_time(env.data$date, "m d y")
env.data$doc[which(env.data$doc == "**")] <- NA
env.data$doc <- as.numeric(env.data$doc)
summary(env.data)
design <- read.csv(file = "data/design.csv")
design <- left_join(design, env.data[,c("sample.id", "date")])
env.data <- env.data[-which(!(env.data$date %in% design$date)),]
```

# Characterize Temporal Dynamics (Abundance-based)
```{r}
# never active
transients <- OTUs.REL.total[,which(colSums(OTUs.REL.active) == 0)]
transients.dist <- vegdist(transients, method = "bray")
transients.pcoa <- cmdscale(transients.dist, eig = T)
var1 <- round(eigenvals(transients.pcoa)[1] / sum(eigenvals(transients.pcoa)), 3) * 100
var2 <- round(eigenvals(transients.pcoa)[2] / sum(eigenvals(transients.pcoa)), 3) * 100
transients.traj <- transients.pcoa$points
colnames(transients.traj) <- c("Comp.1", "Comp.2")
transients.traj.df <- cbind.data.frame(
  sample.id = design$sample.id[which(design$sample.type == "RNA")], transients.traj) 


filter(design, sample.type == "RNA") %>% 
  full_join(transients.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_point() + 
  scale_color_viridis(discrete = T, "Month") + 
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) + 
  coord_fixed()


# present, but not active
seedbank <- OTUs.REL.active == 0 & OTUs.REL.total != 0
seedbank <- seedbank * OTUs.REL.total
seedbank <- seedbank[,which(colSums(seedbank) > 0)]

seedbank.dist <- vegdist(seedbank, method = "bray")
seedbank.pcoa <- cmdscale(seedbank.dist, eig = T)
var1 <- round(eigenvals(seedbank.pcoa)[1] / sum(eigenvals(seedbank.pcoa)), 3) * 100
var2 <- round(eigenvals(seedbank.pcoa)[2] / sum(eigenvals(seedbank.pcoa)), 3) * 100
seedbank.traj <- seedbank.pcoa$points
colnames(seedbank.traj) <- c("Comp.1", "Comp.2")

png(filename = "figures/seedbank-dynamics.png", height = 8, width = 6, units = 'in', res = 300)
par(mfrow = c(3,1), mar = c(3,5,1,1), oma = c(2,2,2,2))
plot(env.data$sample.id, env.data$temp, type = 'l', ylab = "Temperature (C)", xaxt = "n", xlab = "", cex.lab = 1.3)
plot(rowSums(seedbank > 0), type = 'l', xaxt = "n", ylab = "Seedbank Richness", xlab = "", cex.lab = 1.3)
plot(seedbank.traj[,1], type = 'l', ylab = "Seedbank PC1", cex.lab = 1.3)
mtext("Time (Week)", side = 1, line = 3)
dev.off()

seedbank.traj.df <- cbind.data.frame(
  sample.id = design$sample.id[which(design$sample.type == "RNA")], seedbank.traj) 
filter(design, sample.type == "RNA") %>% 
  full_join(seedbank.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>%
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_path(arrow = arrow(angle = 15, length = unit(0.1, "inches"),
                          ends = "last", type = "closed")) + 
  scale_color_viridis(discrete = T, "Month") + 
  geom_point(aes(x = seedbank.traj.df$Comp.1[1], 
                 y = seedbank.traj.df$Comp.2[1]),
             color = viridis(2)[1], size = 3) +
  geom_point(aes(x = seedbank.traj.df$Comp.1[123], 
                 y = seedbank.traj.df$Comp.2[123]),
             color = viridis(2)[2], size = 3) +
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) +
  coord_fixed() +
  ggsave("figures/seedbank_trajectory.pdf", bg = "white", height = 8, width = 10)

filter(design, sample.type == "RNA") %>% 
  full_join(seedbank.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_point() + 
  scale_color_viridis(discrete = T, "Month") + 
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) + 
  stat_ellipse() +
  coord_fixed() +
  ggsave("figures/seedbank_pcoa.pdf", bg = "white", height = 8, width = 10)


# seedbank.groups <- filter(design, sample.type == "RNA") %>% 
#   full_join(seedbank.traj.df) %>% 
#   mutate(month = month(date, label = T, abbr = T)) %>% 
#   select(month)
# seedbank.groups <- factor(seedbank.groups$month)
# sb.bdisp <- betadisper(seedbank.dist, group = seedbank.groups)
# plot(sb.bdisp)
# anova(sb.bdisp)
# boxplot(sb.bdisp)

OTUs.dist <- vegdist(OTUs.REL, method = "bray")
OTUs.pcoa <- cmdscale(OTUs.dist, eig = T)
var1 <- round(eigenvals(OTUs.pcoa)[1] / sum(eigenvals(OTUs.pcoa)), 3) * 100
var2 <- round(eigenvals(OTUs.pcoa)[2] / sum(eigenvals(OTUs.pcoa)), 3) * 100
OTUs.traj <- OTUs.pcoa$points
colnames(OTUs.traj) <- c("Comp.1", "Comp.2")
active.traj <- OTUs.traj[which(design$sample.type == "RNA"),]
total.traj <- OTUs.traj[which(design$sample.type == "DNA"),]

active.traj.df <- cbind.data.frame(
  sample.id = design$sample.id[which(design$sample.type == "RNA")], active.traj) 
full_join(design[which(design$sample.type == "RNA"),], active.traj.df) %>%
  ggplot(aes(x = Comp.1, y = Comp.2, color = sample.id)) + 
  geom_path(arrow = arrow(angle = 15, length = unit(0.1, "inches"),
                  ends = "last", type = "closed")) + 
  scale_color_gradientn(colors = viridis(125), "Sample Number") + 
  geom_point(aes(x = active.traj.df$Comp.1[1], y = active.traj.df$Comp.2[1]),
             color = viridis(2)[1], size = 3) +
  geom_point(aes(x = active.traj.df$Comp.1[123], y = active.traj.df$Comp.2[123]),
             color = viridis(2)[2], size = 3) +
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) +
  coord_fixed() +
  ggsave("figures/active_trajectory.pdf", bg = "white", height = 8, width = 10)

total.traj.df <- cbind.data.frame(
  sample.id = design$sample.id[which(design$sample.type == "DNA")], total.traj) 
full_join(design[which(design$sample.type == "DNA"),], total.traj.df) %>%
  ggplot(aes(x = Comp.1, y = Comp.2, color = sample.id)) + 
  geom_path(arrow = arrow(angle = 15, length = unit(0.1, "inches"),
                          ends = "last", type = "closed")) + 
  scale_color_gradientn(colors = magma(125)) + 
  geom_point(aes(x = total.traj.df$Comp.1[1], y = total.traj.df$Comp.2[1]),
             color = magma(2)[1], size = 3) +
  geom_point(aes(x = total.traj.df$Comp.1[123], y = total.traj.df$Comp.2[123]),
             color = magma(2)[2], size = 3) +
  theme_cowplot()+
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) + 
  coord_fixed() +
  ggsave("figures/total_trajectory.pdf", bg = "white", height = 8, width = 10)


# Points colored by month
# Active
filter(design, sample.type == "RNA") %>% 
  full_join(active.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_point() + 
  scale_color_viridis(discrete = T, "Month") + 
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) +
  stat_ellipse() +
  coord_fixed() +
  ggsave("figures/active_pcoa.pdf", bg = "white", height = 8, width = 10)

# total
filter(design, sample.type == "DNA") %>% 
  full_join(total.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_point() + 
  scale_color_viridis(discrete = T, "Month") + 
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) +
  stat_ellipse() +
  coord_fixed() +
  ggsave("figures/total_pcoa.pdf", bg = "white", height = 8, width = 10)


# active.groups <- filter(design, sample.type == "RNA") %>% 
#   full_join(active.traj.df) %>% 
#   mutate(month = month(date, label = T, abbr = T)) %>% 
#   select(month)
# active.groups <- factor(active.groups$month)
# active.dist <- vegdist(OTUs.REL.active, method = "bray")
# active.bdisp <- betadisper(active.dist, group = active.groups)
# plot(active.bdisp)
# anova(active.bdisp)
# boxplot(active.bdisp)


# total.groups <- filter(design, sample.type == "RNA") %>% 
#   full_join(total.traj.df) %>% 
#   mutate(month = month(date, label = T, abbr = T)) %>% 
#   select(month)
# total.groups <- factor(total.groups$month)
# total.dist <- vegdist(OTUs.REL.total, method = "bray")
# total.bdisp <- betadisper(total.dist, group = total.groups)
# plot(total.bdisp)
# anova(total.bdisp)
# boxplot(total.bdisp)

pc1.dyn <- rbind.data.frame(cbind.data.frame(total.traj.df, subset = "total"), 
                 cbind.data.frame(active.traj.df, subset = "active")) %>% 
  ggplot(aes(x = sample.id, y = Comp.1, color = subset)) + 
  geom_line(size = 0.75) + 
  scale_color_manual("Community Subset", values = c("grey50", "black")) + 
  ylab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  xlab("") + 
  theme(legend.direction = "vertical", legend.position = "right")

pc2.dyn <- rbind.data.frame(cbind.data.frame(total.traj.df, subset = "total"), 
                 cbind.data.frame(active.traj.df, subset = "active")) %>% 
  ggplot(aes(x = sample.id, y = Comp.2, color = subset)) + 
  geom_line(size = 0.75) + 
  scale_color_manual("Community Subset", values = c("grey50", "black")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) + 
  xlab("Time (Week)")

plots <- plot_grid(pc1.dyn + theme(legend.position = "none"), 
          pc2.dyn + theme(legend.position = "none"), nrow = 2, align = 'hv', axis = 'l',
          labels = c("A", "B"))
plots + ggsave(filename = "figures/pcoa_dynamics.pdf", width = 8, height = 8, units = "in")
```

# Ordinations (Presence-absence based)
```{r}
# never active
transients.pa <- OTUs.REL.total[,which(colSums(OTUs.REL.active) == 0)]
transients.pa.dist <- vegdist(transients.pa, method = "bray", binary = T)
transients.pa.pcoa <- cmdscale(transients.pa.dist, eig = T)
var1 <- round(eigenvals(transients.pa.pcoa)[1] / sum(eigenvals(transients.pa.pcoa)), 3) * 100
var2 <- round(eigenvals(transients.pa.pcoa)[2] / sum(eigenvals(transients.pa.pcoa)), 3) * 100
transients.pa.traj <- transients.pa.pcoa$points
colnames(transients.pa.traj) <- c("Comp.1", "Comp.2")
transients.pa.traj.df <- cbind.data.frame(
  sample.id = design$sample.id[which(design$sample.type == "RNA")], transients.pa.traj) 

filter(design, sample.type == "RNA") %>% 
  full_join(transients.pa.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_point() + 
  scale_color_viridis(discrete = T, "Month") + 
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) +
  stat_ellipse() +
  coord_fixed() +
  ggsave("figures/seedbank_pcoa_presence-absence.pdf", bg = "white", height = 8, width = 10)


# present, but not active
seedbank.pa <- OTUs.REL.active == 0 & OTUs.REL.total != 0
seedbank.pa <- seedbank.pa * OTUs.REL.total
seedbank.pa <- seedbank.pa[,which(colSums(seedbank.pa) > 0)]

seedbank.pa.dist <- vegdist(seedbank.pa, method = "bray", binary = T)
seedbank.pa.pcoa <- cmdscale(seedbank.pa.dist, eig = T)
var1 <- round(eigenvals(seedbank.pa.pcoa)[1] / sum(eigenvals(seedbank.pa.pcoa)), 3) * 100
var2 <- round(eigenvals(seedbank.pa.pcoa)[2] / sum(eigenvals(seedbank.pa.pcoa)), 3) * 100
seedbank.pa.traj <- seedbank.pa.pcoa$points
colnames(seedbank.pa.traj) <- c("Comp.1", "Comp.2")

seedbank.pa.traj.df <- cbind.data.frame(
  sample.id = design$sample.id[which(design$sample.type == "RNA")], seedbank.pa.traj) 
filter(design, sample.type == "RNA") %>% 
  full_join(seedbank.pa.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_path(arrow = arrow(angle = 15, length = unit(0.1, "inches"),
                          ends = "last", type = "closed")) + 
  scale_color_viridis(discrete = T, "Month") + 
  geom_point(aes(x = seedbank.pa.traj.df$Comp.1[1], 
                 y = seedbank.pa.traj.df$Comp.2[1]),
             color = viridis(2)[1], size = 3) +
  geom_point(aes(x = seedbank.pa.traj.df$Comp.1[123], 
                 y = seedbank.pa.traj.df$Comp.2[123]),
             color = viridis(2)[2], size = 3) +
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = ""))

filter(design, sample.type == "RNA") %>% 
  full_join(seedbank.pa.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_point() + 
  scale_color_viridis(discrete = T, "Month") + 
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) + 
  stat_ellipse() +
  coord_fixed() +
  ggsave("figures/seedbank_pcoa_presence-absence.pdf", bg = "white", height = 8, width = 10)
  


OTUs.pa.dist <- vegdist(OTUs.REL, method = "bray", binary = T)
OTUs.pa.pcoa <- cmdscale(OTUs.pa.dist, eig = T)
var1 <- round(eigenvals(OTUs.pa.pcoa)[1] / sum(eigenvals(OTUs.pa.pcoa)), 3) * 100
var2 <- round(eigenvals(OTUs.pa.pcoa)[2] / sum(eigenvals(OTUs.pa.pcoa)), 3) * 100
OTUs.pa.traj <- OTUs.pa.pcoa$points
colnames(OTUs.pa.traj) <- c("Comp.1", "Comp.2")
active.pa.traj <- OTUs.pa.traj[which(design$sample.type == "RNA"),]
total.pa.traj <- OTUs.pa.traj[which(design$sample.type == "DNA"),]

active.pa.traj.df <- cbind.data.frame(
  sample.id = design$sample.id[which(design$sample.type == "RNA")], active.pa.traj) 
full_join(design[which(design$sample.type == "RNA"),], active.pa.traj.df) %>%
  ggplot(aes(x = Comp.1, y = Comp.2, color = sample.id)) + 
  geom_path(arrow = arrow(angle = 15, length = unit(0.1, "inches"),
                  ends = "last", type = "closed")) + 
  scale_color_gradientn(colors = viridis(125), "Sample Number") + 
  geom_point(aes(x = active.pa.traj.df$Comp.1[1], y = active.pa.traj.df$Comp.2[1]),
             color = viridis(2)[1], size = 3) +
  geom_point(aes(x = active.pa.traj.df$Comp.1[123], y = active.pa.traj.df$Comp.2[123]),
             color = viridis(2)[2], size = 3) +
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = ""))

total.pa.traj.df <- cbind.data.frame(
  sample.id = design$sample.id[which(design$sample.type == "DNA")], total.pa.traj) 
full_join(design[which(design$sample.type == "DNA"),], total.pa.traj.df) %>%
  ggplot(aes(x = Comp.1, y = Comp.2, color = sample.id)) + 
  geom_path(arrow = arrow(angle = 15, length = unit(0.1, "inches"),
                          ends = "last", type = "closed")) + 
  scale_color_gradientn(colors = magma(125)) + 
  geom_point(aes(x = total.pa.traj.df$Comp.1[1], y = total.pa.traj.df$Comp.2[1]),
             color = magma(2)[1], size = 3) +
  geom_point(aes(x = total.pa.traj.df$Comp.1[123], y = total.pa.traj.df$Comp.2[123]),
             color = magma(2)[2], size = 3) +
  theme_cowplot()+
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = ""))


filter(design, sample.type == "RNA") %>% 
  full_join(active.pa.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_point() + 
  scale_color_viridis(discrete = T, "Month") + 
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) +
  stat_ellipse() +
  coord_fixed() +
  ggsave("figures/active_pcoa_presence-absence.pdf", bg = "white", height = 8, width = 10)


filter(design, sample.type == "DNA") %>% 
  full_join(total.pa.traj.df) %>% 
  mutate(month = month(date, label = T, abbr = T)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2, color = month)) + 
  geom_point() + 
  scale_color_viridis(discrete = T, "Month") + 
  theme_cowplot() + 
  xlab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) +
  stat_ellipse() +
  coord_fixed() +
  ggsave("figures/total_pcoa_presence-absence.pdf", bg = "white", height = 8, width = 10)


pc1.pa.dyn <- rbind.data.frame(cbind.data.frame(total.pa.traj.df, subset = "total.pa"), 
                 cbind.data.frame(active.pa.traj.df, subset = "active.pa")) %>% 
  ggplot(aes(x = sample.id, y = Comp.1, color = subset)) + 
  geom_line(size = 0.75) + 
  scale_color_manual("Community Subset", values = c("grey50", "black")) + 
  ylab(paste("PCoA 1 (",var1,"%)", sep = "")) + 
  xlab("") + 
  theme(legend.direction = "vertical", legend.position = "right")

pc2.pa.dyn <- rbind.data.frame(cbind.data.frame(total.pa.traj.df, subset = "total.pa"), 
                 cbind.data.frame(active.pa.traj.df, subset = "active.pa")) %>% 
  ggplot(aes(x = sample.id, y = Comp.2, color = subset)) + 
  geom_line(size = 0.75) + 
  scale_color_manual("Community Subset", values = c("grey50", "black")) + 
  ylab(paste("PCoA 2 (",var2,"%)", sep = "")) + 
  xlab("Time (Week)")
plots.pa <- plot_grid(pc1.pa.dyn + theme(legend.position = "none"), 
          pc2.pa.dyn + theme(legend.position = "none"), nrow = 2, align = 'hv', axis = 'l',
          labels = c("A", "B"))
plots.pa %>% ggsave(filename = "figures/pcoa_dynamics_presence-absence.pdf", width = 8, height = 8, units = "in", bg = "white")
```


## organize data structure for codyn
```{r}
OTUs.long <- as.data.frame(OTUs.REL)
OTUs.long$mol <- design$sample.type
OTUs.long$number <- design$sample.id
OTUs.long <- gather(OTUs.long, key = otu, value = abundance, -mol, -number)

# Calculate turnover
turn.total <- turnover(df = OTUs.long, 
                 time.var = "number",
                 species.var = "otu",
                 abundance.var = "abundance",
                 replicate.var = "mol")
turn.appear <- turnover(df = OTUs.long, 
                       time.var = "number",
                       species.var = "otu",
                       abundance.var = "abundance",
                       replicate.var = "mol",
                       metric = "appearance")
turn.disappear <- turnover(df = OTUs.long, 
                       time.var = "number",
                       species.var = "otu",
                       abundance.var = "abundance",
                       replicate.var = "mol",
                       metric = "disappearance")

# Make figure showing turnover in different subsets
turn.total %>% mutate(Molecule = mol) %>%
  ggplot(aes(y = total, x = number, color = Molecule))+
  geom_point(size = .75, alpha = 0.5) + 
  geom_smooth(method = "loess") + 
  ylab("Turnover") + 
  xlab("Time (Week)") +
  scale_color_manual("Community Subset", values = c("grey50", "black")) +
  ggsave("figures/turnover-total.pdf", height = 6, width = 8, bg = "white")
ggplot(turn.appear, aes(y = appearance, x = number, color = mol))+
  geom_smooth() + 
  geom_point()
ggplot(turn.disappear, aes(y = disappearance, x = number, color = mol))+
  geom_smooth() + 
  geom_point()

dates <- left_join(design[-which(design$sample.id == 1),], env.data) %>% select(date)
turn.total$Season <- ifelse(month(dates$date) %in% c(5:10), "Summer", "Winter")
group_by(turn.total, mol, Season) %>% 
  summarise(
    mean = mean(total),
    cv = sd(total)/mean)

turn.total %>% group_by(mol) %>% summarize(avg.turn = mean(total))
# Mean Rank Shift
ul.mrs <- rank_shift(df = OTUs.long,
           time.var = "number",
           species.var = "otu",
           abundance.var = "abundance",
           replicate.var = "mol")

ul.mrs$year <- as.numeric(colsplit(ul.mrs$year_pair, pattern = "-", names = c("year1", "year2"))[,2])
names(ul.mrs)[3] <- "Molecule"

# Create plot
ggplot(ul.mrs, aes(x = year, y = MRS, color = Molecule)) + 
  geom_line(size = .6, alpha = 0.75) +
  xlab("Time (Week)") + 
  ylab("Mean Rank Shift") +
  theme_cowplot() +
  scale_color_manual("Community Subset", values = c("grey50", "black")) +
  ggsave("figures/mean_rank_shift.pdf", bg = "white", height = 6, width = 8)



# Does one plot type show higher or lower MRS, on average?
dates <- left_join(design[-which(design$sample.id == 1),], env.data) %>% select(date)

ul.mrs$Season <- ifelse(month(dates$date) %in% c(5:10), "Summer", "Winter")
group_by(ul.mrs, Molecule, Season) %>% 
  summarise(
    mean = mean(MRS),
    cv = sd(MRS)/mean)


# # Rate change interval
# ul.rci <- rate_change_interval(df = OTUs.long,
#                      time.var = "number",
#                      species.var = "otu", 
#                      abundance.var = "abundance",
#                      replicate.var = "mol")
# 
# ul.rci
# rate.plot <- ggplot(ul.rci, aes(interval, distance)) +
#   geom_point() + 
#   facet_wrap(~mol) +
#   theme(strip.text.x = element_text(size = 7)) +
#   stat_smooth(method = "loess", se = F, size = 1) + 
#   ylab("Hellinger Distance") + 
#   xlab("Time Interval (Weeks)") +
#   theme_minimal()
# rate.plot
```

# Partition nestedness and turnover
```{r}
OTUs.pa <- decostand(OTUs.active, method = "pa")
OTUs.betapart <- beta.pair(x = OTUs.pa, index.family = "sorensen")
OTUs.nest <- OTUs.betapart$beta.sne
OTUs.turn <- OTUs.betapart$beta.sim
OTUs.sor <- OTUs.betapart$beta.sor

samplingdays <- env.data$date
time.dist <- matrix(NA, nrow = length(samplingdays), ncol = length(samplingdays))
for(i in 1:length(samplingdays)){
  for(j in 1:length(samplingdays)){
    time.dist[i,j] <- (samplingdays[i] - samplingdays[j])
  }
}
time.dist <- as.dist(time.dist)

env.vars <- env.data[c("temp", "spc", "oxygen", "secchi", "ph", "tp", "tn", "doc")]
env.dist <- daisy(scale(env.vars), metric = "gower")
timeddr <- data.frame(Turnover = as.vector(OTUs.turn), 
           Nestedness = as.vector(OTUs.nest),
           Sorensen = as.vector(OTUs.sor),
           EnvDist = as.vector(env.dist), 
           Time = as.vector(time.dist))

turn.time.mod <- (lm(Turnover ~ Time + I(Time^2) + I(Time^3) + I(Time^4) + I(Time^5), data = timeddr))
summary(turn.time.mod)
newdf <- data.frame(Time = min(timeddr$Time):max(timeddr$Time))
preds <- predict(turn.time.mod, newdf)
plot(Turnover ~ Time, timeddr, col = "gray70")
lines(newdf$Time, preds, lwd = 2)

env.time.mod <- (lm(EnvDist ~ Time + I(Time^2) + I(Time^3) + I(Time^4) + I(Time^5), data = timeddr))
summary(env.time.mod)
newdf <- data.frame(Time = min(timeddr$Time):max(timeddr$Time))
preds <- predict(env.time.mod, newdf)
plot(EnvDist ~ Time, timeddr, col = "gray70")
lines(newdf$Time, preds, lwd = 2)

plot(env.time.mod)

turn.env.mod <- lm(resid(turn.time.mod) ~ resid(env.time.mod))
summary(turn.env.mod)
plot(resid(env.time.mod), resid(turn.time.mod))

nest.time.mod <- (lm(Nestedness ~ Time, data = timeddr))
summary(nest.time.mod)
newdf <- data.frame(Time = min(timeddr$Time):max(timeddr$Time))
preds <- predict(nest.time.mod, newdf)
plot(Nestedness ~ Time, timeddr, col = "gray70")
lines(newdf$Time, preds, lwd = 2)

nest.env.mod <- lm(resid(nest.time.mod) ~ resid(env.time.mod))
summary(nest.env.mod)
plot(resid(env.time.mod), resid(nest.time.mod))
  
timeddr %>% gather(key = Partition, value = Beta, -EnvDist, -Time) %>% 
  ggplot(aes(x = EnvDist, y = Beta, color = Partition)) + 
  geom_point(alpha = 0.1) +
  geom_smooth(size = 2)
```


# Calculate Negative Frequency Dependence in Common versus Rare Taxa
```{r}
calc.neg.freq.dep <- function(sbs){
  y.s <- matrix(ncol = ncol(sbs), nrow = nrow(sbs)-1)
  for(i in 1:(nrow(sbs)-1)){
    y.s[i,] = log(sbs[i+1,] / sbs[i,])
  }
  eq.freq <- vector(length = ncol(y.s))
  fd <- vector(length = ncol(y.s))
  sbs.rel <- decostand(sbs[-nrow(sbs),], method = "total")
  for(i in 1:ncol(y.s)){
    mod <- lm(y.s[,i] ~ sbs.rel[,i])
    eq.freq[i] <- -coef(mod)[1] / coef(mod)[2]
    fd[i] <- coef(mod)[2]
  }
  # plot(log10(eq.freq), log10(-fd), 
  #      ylab = "log10 Negative Freq. Dependence",
  #      xlab = "log10 Equilibrium Frequency")
  return(na.omit(cbind.data.frame(eq.freq, fd)))
}

shuffle.ts <- function(species.ts){
  species.ts[sample(1:length(species.ts))]
}

get.null.distr <- function(comm, iters = 5000){
  pb <- progress_bar$new(total = iters)
  nfd.cov <- rep(NA, iters)
  for(i in 1:iters){
    nullcom <- apply(comm, MARGIN = 2, FUN = shuffle.ts) # randomize sampling order
    nfd <- calc.neg.freq.dep(nullcom)
    nfd %>% filter(eq.freq > 10^-9) %>% filter(-fd > 0) -> nfd
    nfd.cov[i] <- cov(log(nfd$eq.freq), log(-nfd$fd))
    pb$tick()
  }
  return(nfd.cov)
}

OTUs.ranked <- OTUs.total[,names(sort(colSums(OTUs.total), decreasing = T))]

# separate OTUs present across the nearly whole time series
OTUs.total.persistent <- OTUs.ranked[,which(
  colMeans(decostand(OTUs.ranked, method = "pa")) >= 0.9)]
OTUs.active.persistent <- OTUs.active[,colnames(OTUs.total.persistent)]

# How many taxa to consider?
(otu.thresh <- min(25, ncol(OTUs.total.persistent)))

OTUs.total.nozero <- OTUs.total.persistent[,1:otu.thresh] + 10^-10
OTUs.REL.total.nozero <- decostand(OTUs.total[,1:otu.thresh], method = "total") + 10^-10

nfd.total <- calc.neg.freq.dep(OTUs.total.nozero)
nfd.total %>% filter(eq.freq > 10^-9) %>% filter(-fd > 0) -> nfd.total
nfd.total.cov <- cov(log(nfd.total$eq.freq), log(-nfd.total$fd))
nfd.total %>% ggplot(aes(x = eq.freq, y = -fd)) +
  geom_point() + 
  scale_y_log10() + 
  scale_x_log10() +
  geom_smooth(method = "lm") + 
  ylab("Negative Frequency Dependence") + 
  xlab("Equilibrium Frequency")

OTUs.active.nozero <- OTUs.active.persistent[,1:otu.thresh] + 10^-10
OTUs.REL.active.nozero <- decostand(OTUs.active[,1:otu.thresh], method = "total") + 10^-10

nfd.active <- calc.neg.freq.dep(OTUs.active.nozero)
nfd.active %>% filter(eq.freq > 10^-9) %>% filter(-fd > 0) -> nfd.active
nfd.active.cov <- cov(log(nfd.active$eq.freq), log(-nfd.active$fd))
nfd.active %>% ggplot(aes(x = eq.freq, y = -fd)) +
  geom_point() + 
  scale_y_log10() + 
  scale_x_log10() +
  geom_smooth(method = "lm") + 
  ylab("Negative Frequency Dependence") + 
  xlab("Equilibrium Frequency")

# OTUs.seedbank.nozero <- seedbank[,1:otu.thresh] + 10^-10
# OTUs.REL.seedbank.nozero <- decostand(seedbank[,1:otu.thresh], method = "total") + 10^-10
# nfd.sb <- calc.neg.freq.dep(OTUs.seedbank.nozero)
# nfd.sb %>% filter(eq.freq > 10^-9) %>% filter(-fd > 0) -> nfd.sb
# nfd.sb.cov <- cov(log(nfd.sb$eq.freq), log(-nfd.sb$fd))
# nfd.sb %>% ggplot(aes(x = eq.freq, y = -fd)) +
#   geom_point() + 
#   scale_y_log10() + 
#   scale_x_log10() +
#   ylab("Negative Frequency Dependence") + 
#   xlab("Equilibrium Frequency")


# Generate null distributions
iternum <- 999
tot.nd <- get.null.distr(comm = OTUs.total.nozero, iters = iternum)
act.nd <- get.null.distr(comm = OTUs.active.nozero, iters = iternum)
# sb.nd <- get.null.distr(comm = OTUs.seedbank.nozero, iters = iternum)

# Compare observed with null
hist(tot.nd, breaks = 20); abline(v = nfd.total.cov, col = "red")
(tot.nfd.pval <- rank(c(nfd.total.cov, tot.nd))[1] / length(c(nfd.total.cov, tot.nd)))
hist(act.nd, breaks = 20); abline(v = nfd.active.cov, col = "red")
(act.nfd.pval <- rank(c(nfd.active.cov, act.nd))[1] / length(c(nfd.active.cov, act.nd)))
# hist(sb.nd, breaks = 20); abline(v = nfd.sb.cov, col = "red")
# (sb.nfd.pval <- rank(c(nfd.sb.cov, sb.nd))[1] / length(c(nfd.sb.cov, sb.nd)))

# nfd.obs <- rbind.data.frame(cbind.data.frame(subset = "Total", nfd = nfd.total.cov),
#                  cbind.data.frame(subset = "Active", nfd = nfd.active.cov),
#                  cbind.data.frame(subset = "Seed Bank", nfd = nfd.sb.cov)) 
# 
# nfd.nulldists <- rbind.data.frame(cbind.data.frame(subset = "Total", nfd = tot.nd),
#                  cbind.data.frame(subset = "Active", nfd = act.nd),
#                  cbind.data.frame(subset = "Seed Bank", nfd = sb.nd)) 

nfd.obs <- rbind.data.frame(cbind.data.frame(subset = "Total", nfd = nfd.total.cov),
                 cbind.data.frame(subset = "Active", nfd = nfd.active.cov)) 

nfd.nulldists <- rbind.data.frame(cbind.data.frame(subset = "Total", nfd = tot.nd),
                 cbind.data.frame(subset = "Active", nfd = act.nd)) 

nfd.nulldists %>% 
  ggplot(aes(y = nfd, x = subset)) + 
  geom_jitter(color = "grey", alpha = 0.1) + 
  geom_violin(alpha = 0.7) + 
  geom_point(data = nfd.obs, aes(x = subset, y = nfd), 
             color = "black", size = 5) + 
  ylab("Negative Frequency Dependence") + 
  xlab("Community Subset") + 
  ggsave("figures/negative_freq_depend.pdf", bg = "white", width = 6, height = 6, units = "in")

# Calculate standardized effect sizes
nfd.summary <- nfd.nulldists %>% 
  group_by(subset) %>% summarize(mean.nfd = mean(nfd), sd.nfd = sd(nfd)) %>% 
  left_join(nfd.obs) %>% mutate(nfd.ses = (nfd - mean.nfd)/sd.nfd)
nfd.summary
```

```{r}
# What is the effect of taxa number on response
nfd.response <- function(OTUs = NULL, OTUs.active = NULL, num.seq = 10, num.iter = 999, plotit = F, incidence.freq = 0.9, max.taxa = NULL){
  
  # separate OTUs present across the whole time series
  OTUs.ranked <- OTUs[,names(sort(colSums(OTUs), decreasing = T))]
  OTUs.persistent <- OTUs.ranked[,which(
    colMeans(decostand(OTUs.ranked, method = "pa")) >= incidence.freq)]
  
  # If we're looking at Active OTUs, make the switch here
  if(!is.null(OTUs.active)){
    if(is.null(OTUs)) print("please supply total otu table")
    OTUs.persistent <- OTUs.active[,colnames(OTUs.persistent)]
  }
  
  # decide how many values of cutoffs to test
  max.taxa <- floor(seq(3, min(max.taxa, ncol(OTUs.persistent)), length.out = num.seq))
  output <- data.frame(taxa = max.taxa)
  
  # loop through different otu thresholds
  for(i in 1:length(max.taxa)){
    if(max.taxa[i] > ncol(OTUs.persistent)) return(output)
    otu.thresh <- min(max.taxa[i], ncol(OTUs.persistent))
    OTUs.nozero <- OTUs.persistent[,1:otu.thresh] + 10^-10
    nfd <- calc.neg.freq.dep(OTUs.nozero)
    nfd <- nfd %>% filter(eq.freq > 10^-9) %>% filter(-fd > 0)
    nfd.cov <- cov(log(nfd$eq.freq), log(-nfd$fd))
    
    if(plotit){
      nfd %>% 
        ggplot(aes(x = eq.freq, y = -fd)) +
        geom_point() + 
        scale_y_log10() + 
        scale_x_log10() +
        geom_smooth(method = "lm") + 
        ylab("Negative Frequency Dependence") + 
        xlab("Equilibrium Frequency")
    }
    
    nd <- get.null.distr(comm = OTUs.nozero, iters = num.iter)
    nfd.ses <- (nfd.cov - mean(nd)/sd(nd))
    nfd.pval <- rank(c(nfd.cov, nd))[1] / length(c(nfd.cov, nd))
    cov.strength <- nfd.cov / mean(nd)
    se <- sd(nd)/sqrt(num.iter)
    output[i,"p"] <- nfd.pval
    output[i,"ses"] <- nfd.ses
    output[i,"strength"] <- cov.strength
    output[i,"stderr"] <- se
    output[i,"mean"] <- mean(nd)
    output[i,"nfdcov"] <- nfd.cov
  }
  
  return(output)
}


active.nfd.response <- nfd.response(OTUs = OTUs.total, OTUs.active = OTUs.active, num.seq = 30, num.iter = 999, max.taxa = 100)
total.nfd.response <- nfd.response(OTUs = OTUs.total, OTUs.active = NULL, num.seq = 30, num.iter = 999, max.taxa = 100)
saveRDS(active.nfd.response, file = "analysis/temp-results/nfd_response_active.rda")
saveRDS(total.nfd.response, file = "analysis/temp-results/nfd_response_total.rda")
active.nfd.response <- readRDS(file = "analysis/temp-results/nfd_response_active.rda")
total.nfd.response <- readRDS(file = "analysis/temp-results/nfd_response_total.rda")

nfd.response.df <- rbind.data.frame(
  cbind.data.frame(subset = "active", active.nfd.response),
  cbind.data.frame(subset = "total", total.nfd.response))
nfd.response.df %>% 
#  filter(p < 0.05) %>% 
  ggplot(aes(x = taxa, y = strength, color = subset)) +
  geom_point() +
  geom_smooth()

cbind.data.frame(taxa = active.nfd.response$taxa, 
      strength = active.nfd.response$strength / total.nfd.response$strength) %>% 
  ggplot(aes(x = taxa, y = strength)) +
  geom_point() +
  geom_abline(slope = 0, intercept = 1, color = "gray") +
  geom_smooth(method = "loess")
```

# Reappeareance Scores
```{r}
# Calculate a species 

reappearance.score <- function(DNA, RNA){
  # calculate # of times present but not active
  otu.diff <- decostand((DNA + RNA), method = "pa") - decostand(RNA, method = "pa")
  otu.diff.weighted <- otu.diff # * decostand(DNA, method = "total")
  return(colSums(otu.diff.weighted))
}

calc.score <- function(species){
  length()
}

(OTUs.total - OTUs.active)[,1]
reappearance.score <- function(DNA, RNA){
  
  otu.diff <- decostand((DNA + RNA), method = "pa") - 
    decostand(RNA, method = "pa")
  otuscores <- vector(length = ncol(otu.diff))
  
  for(j in 1:ncol(otu.diff)){
    otuscore <- 0
    for(i in 1:(nrow(otu.diff)-1)){
      if(length(unique(otu.diff[c(i,i+1), j])) > 1){
        otuscore <- otuscore + 1
      }
    }
    otuscores[j] <- otuscore
    print(paste("completed otu #", j))
  }
  
  return(otuscores)
}

otu.reap <- reappearance.score(DNA = OTUs.total, RNA = OTUs.active)
otu.pres <- colSums(decostand((OTUs.total + OTUs.active), method = "pa"))
plot(otu.pres, otu.reap/otu.pres, ylab = "# of times present in seed bank but not active",
     xlab = "# of times present in lake")

cbind.data.frame(times_inactive = otu.reap, presences = otu.pres) %>%
  mutate(prop_inactive = times_inactive/presences, 
         incidence = presences / (length(env.data$date) - 1)) %>% 
  ggplot(aes(y = prop_inactive, x = incidence)) + 
  geom_jitter(width = 0.005, height = 0.005, alpha = 0.1) + 
  geom_smooth() + 
  ylab("Inactive Frequency") +
  xlab("Incidence in Total Community") + 
  ggsave("figures/incidence_by_inactivity.pdf", bg = "white", width = 6, height = 6)

subset(OTUs.tax, OTU %in% names(sort(otu.reap, decreasing = T)[1:20]))

# pull out taxa who are present > 50% of time but inactive > 50% of time
# these may be potential seed bankers or sink populations form soils
cbind.data.frame(times_inactive = otu.reap, presences = otu.pres) %>%
  rownames_to_column(var = "OTU") %>% 
  mutate(prop_inactive = times_inactive/presences, 
         incidence = presences / (length(env.data$date) - 1)) %>% 
  filter(incidence > 0.5, prop_inactive > 0.5) -> seedbank.taxa
subset(OTUs.tax, OTU %in% seedbank.taxa$OTU)
```

# Taxa Time Relationship
```{r}
ttr.calc <- function(comm){
  comm.pa <- decostand(comm, method = 'pa')
  weeknum <- 1:nrow(comm.pa)
  otusum <- numeric(nrow(comm.pa))
  for(week in weeknum){
    otusum[week] <- ifelse(week > 1, sum(colSums(comm.pa[1:week,]) > 0), 
                           sum(comm.pa[1,]))
  }
  return(cbind.data.frame(week = weeknum, taxa = otusum))
}

active.ttr <- ttr.calc(OTUs.active)
total.ttr <- ttr.calc(OTUs.total)
transient.ttr <- ttr.calc(transients)

ttrs <- rbind.data.frame(cbind.data.frame(subset = "active", active.ttr),
                 cbind.data.frame(subset = "total", total.ttr),
                 cbind.data.frame(subset = "transients", transient.ttr))
ttrs %>% 
  ggplot(aes(x = week, y = taxa, color = subset)) + 
  geom_line(size = 2)
```

# Conditionally Rare Taxa
```{r}
identifyCRT <- function(spec.dyn){
  n <- length(spec.dyn)
  skew.numer <- sum((spec.dyn - mean(spec.dyn))^3)/n
  skew.denom <- (sum((spec.dyn - mean(spec.dyn))^2)/n)^(3/2)
  kurt.num <- sum((spec.dyn - mean(spec.dyn))^4)/n
  kurt.denom <- (sum((spec.dyn - mean(spec.dyn))^2)/n)^2
  skewness <- skew.numer / skew.denom
  kurtosis <- kurt.num / kurt.denom
  b <- (1 + skewness^2) / (kurtosis + 3)
  return(b)
 }

activeCRTs <- apply(X = OTUs.REL.active, MARGIN = 2, FUN = identifyCRT)
totalCRTs <- apply(X = OTUs.REL.total, MARGIN = 2, FUN = identifyCRT)
hist(activeCRTs)
hist(totalCRTs)
boxplot(activeCRTs - totalCRTs)


candidateCRTs <- names(activeCRTs[which(activeCRTs > 0.9)])
candidateCRTs <- OTUs.REL.active[,candidateCRTs]
candidateCRTs <- candidateCRTs[,apply(candidateCRTs, 2, max) > 0.01]
matplot(candidateCRTs, type = 'l')
subset(OTUs.tax, OTU %in% colnames(candidateCRTs))


```

```{r}
library(glmnet)
library(igraph)
library(gridExtra)

subset.active <- OTUs.active[,which(colMeans(OTUs.active) > 6)]
subset.total <- OTUs.active[,which(colMeans(OTUs.total) > 6)]

subset.active.t <- subset.active[-nrow(subset.active),]
subset.active.t1 <- subset.active[-1,]


```

```{r}
library(cooccur)



active.cooccur <- cooccur(t(decostand(subset.active, method = "pa")), spp_names = TRUE)
summary(active.cooccur)
plot(active.cooccur)
active.coocur.pos <- active.cooccur$results %>% as_tibble() %>% 
  filter(p_lt < 0.05)
active.coocur.neg <- active.cooccur$results %>% as_tibble() %>% 
  filter(p_gt < 0.05)
  
# active.effects <- effect.sizes(active.cooccur)
# 
# active.attr <- pair.attributes(active.cooccur)
# active.attr %>% arrange(num_rand)
active.coocor.spec <- unique(unlist(active.coocur.pos[,1], active.coocur.pos[,2]))
small.subset <- OTUs.active[,active.coocor.spec]
library(G1DBN)
out1 <- DBNScoreStep1(data = small.subset, method = 'ls')
saveRDS(out1, file = "analysis/temp-results/DBNout1active.rda")
alpha1 = 0.5
edgesG1 <- BuildEdges(out1$S1ls, threshold = alpha1, 
                      targetNames = colnames(small.subset),
                      predNames = colnames(small.subset))
edgesG1
S2 <- DBNScoreStep2(out1$S1ls, data = small.subset, alpha1 = alpha1, method = 'ls')
alpha2 = 0.05
edgesG2 <- BuildEdges(score = S2, threshold = alpha2, 
                      targetNames = colnames(small.subset),
                      predNames = colnames(small.subset), prec = 6)

netwG1 <- BuildNetwork(edgesG1, Labels = colnames(small.subset))
netwG2 <- BuildNetwork(edgesG2, Labels = colnames(small.subset))

g2 <- graph.data.frame(netwG2$Edges$List, directed = T)
E(g2)$weight <- as.numeric(netwG2$Edges$List[,3])
l <- layout.fruchterman.reingold(g2, niter=5000)
plot(g2, layout = l, 
     edge.arrow.size = 0.5,
     vertex.label.cex = 0.5,
     vertex.label.font=2,
     vertex.label.font.family="helvetica",
     vertex.shape="circle", 
     vertex.size=1, 
     vertex.label.color="black", 
     edge.width=0.5)

netwG1$Edges$List
pr1 <- PRcurve(score = out1$S1ls, validMat = abs(netwG1$AdjMatrix)>0, dec = F)
plot(pr1$recall, pr1$precision, type = 'l')

```