---
title: "University Lake Respiration"
author: "Mario E. Muscarella"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
   - \usepackage{graphics}
output: 
  pdf_document:
    fig_caption: true
---

Project looking at the temporal dynamics of bacterial respiration in University Lake.


# Initial Setup
```{r results='hide', message=FALSE}
rm(list=ls())
getwd()
setwd("~/GitHub/UniversityLake/analyses")
```

# Load PreSens Package
```{r}
# Inport the function from source file
source("../bin/PreSensInteractiveRegression.r") # Use to pick the time windows
source("../bin/PreSensRespiration.R")


PreSens.Respiration("../data/Respiration/Output/20130419_UL001_Oxygen.txt",
                    "../data/Respiration/Output/20130419_UL001_BR.txt")



input  <-  "../data/Respiration/Output/20130419_UL001_Oxygen.txt"
output <-  "../data/Respiration/Output/20130419_UL001_BR.txt"

in.name <- rep(NA, 24)

wells <- read.delin(infile, header=F, skip=46, sep=";",strip.white=T,
                          stringsAsFactors=FALSE)[,1:29])

in.name <- c(rep("HMWF003", 3), rep("HMWF013", 3), rep("HMWF015", 3),
             rep("HMWF016", 3), rep("HMWF017", 3), rep("HMWF022", 3),
             rep("HMWF036", 3), rep("Blank", 3))

PreSens.Respiration2(infile = input, outfile = output, start = 0,
                                 end = 1, name.in = in.name)




```







```{r}


# Import BR Data
file.path <- "./data/Respiration/"
file.names <- list.files(path = file.path, all.files=FALSE, include.dirs=FALSE,
                         pattern = "\\MEM_Output.txt$", full.names=FALSE,
                         ignore.case=FALSE)

br.names <- rep("NA" , length(file.names))
for (i in 1:length(file.names)){
  br.name <- paste("BR_", substr(file.names[i], 1, 8), "_", i, sep="")
  br.names[i] <- br.name
  temp <- read.csv(paste(file.path, file.names[i], sep= ""), header=T)
  colnames(temp) <- c("Sample", "Start", "End", "Rate", "R2", "P")
  assign(br.name, temp)
}

```
